name: "Upload artifacts"

concurrency: "upload-artifacts"

on:
  workflow_dispatch:
  push:
    paths: ["artifacts/*.md"]
    branches: ["main"]

jobs:
  upload:
    name: "Upload"
    runs-on: ubuntu-latest
    services:
      ipfs-node:
        image: "ipfs/go-ipfs:latest"
        ports:
          - 4001:4001
          - 5001:5001
          - 8080:8080
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Pin to IPFS"
        id: artifact-action
        uses: acearchive/artifact-action@main
        with:
          mode: upload
          ipfs-api: "/dns/ipfs-node/tcp/5001/http"
          pin-endpoint: "https://api.filebase.io/v1/ipfs"
          pin-token: ${{ secrets.FILEBASE_PIN_API_TOKEN }}
      - name: "Publish IPNS name"
        uses: acearchive/w3name-action@main
        with:
          private-key: ${{ secrets.IPNS_KEY }}
          path: ${{ format('/ipfs/{0}', steps.artifact-action.outputs.root-cid) }}
