name: "Upload artifacts"

concurrency: "upload-artifacts"

on:
  workflow_dispatch:
  push:
    paths: ["artifacts/*.md"]
    branches: ["main"]

jobs:
  upload:
    name: "Upload"
    runs-on: ubuntu-latest
    services:
      ipfs-node:
        image: "ipfs/go-ipfs:latest"
        ports:
          - 4001:4001
          - 5001:5001
          - 8080:8080
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Upload"
        uses: acearchive/artifact-action@v0.3.0
        with:
          mode: upload
          ipfs-api: "/dns/ipfs-node/tcp/5001/http"
          w3s-token: ${{ secrets.W3S_API_TOKEN }}
